name: merge
on:
  push:
    branches:
      - 'main'
jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Enable experimental on dockerd
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Make latest release
        run: make release
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          IMAGE_TAG: latest
      - name: Make tagged release
        run: make release
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          IMAGE_TAG: ${{ github.sha }}
